# ============================================================
# Cross.toml (cross-only keys)
# ============================================================

[build]

[target.x86_64-unknown-linux-gnu]
image = "static-cross-x86_64-unknown-linux-gnu:latest"

[target.aarch64-unknown-linux-gnu]
image = "static-cross-aarch64-unknown-linux-gnu:latest"

[target.armv7-unknown-linux-gnueabihf]
image = "static-cross-armv7-unknown-linux-gnueabihf:latest"

[target.i686-unknown-linux-gnu]
image = "static-cross-i686-unknown-linux-gnu:latest"

[target.x86_64-unknown-linux-musl]
image = "static-cross-x86_64-unknown-linux-musl:latest"

[target.aarch64-unknown-linux-musl]
image = "static-cross-aarch64-unknown-linux-musl:latest"

[target.armv7-unknown-linux-musleabihf]
image = "static-cross-armv7-unknown-linux-musleabihf:latest"

[target.aarch64-linux-android]
image = "static-cross-aarch64-linux-android:latest"

[target.armv7-linux-androideabi]
image = "static-cross-armv7-linux-androideabi:latest"

[target.x86_64-linux-android]
image = "static-cross-x86_64-linux-android:latest"

[target.i686-linux-android]
image = "static-cross-i686-linux-android:latest"

[target.x86_64-apple-darwin]
image = "static-cross-x86_64-apple-darwin:latest"

[target.aarch64-apple-darwin]
image = "static-cross-aarch64-apple-darwin:latest"

[target.aarch64-apple-ios]
image = "static-cross-aarch64-apple-ios:latest"

[target.aarch64-apple-ios-sim]
image = "static-cross-aarch64-apple-ios-sim:latest"

[target.x86_64-apple-ios]
image = "static-cross-x86_64-apple-ios:latest"

[target.x86_64-unknown-freebsd]
image = "static-cross-x86_64-unknown-freebsd:latest"

[target.aarch64-unknown-freebsd]
image = "static-cross-aarch64-unknown-freebsd:latest"

[target.x86_64-unknown-netbsd]
image = "static-cross-x86_64-unknown-netbsd:latest"

[target.x86_64-unknown-openbsd]
image = "static-cross-x86_64-unknown-openbsd:latest"

[target.x86_64-unknown-dragonfly]
image = "static-cross-x86_64-unknown-dragonfly:latest"

[target.x86_64-pc-windows-gnu]
image = "static-cross-x86_64-pc-windows-gnu:latest"

[target.i686-pc-windows-gnu]
image = "static-cross-i686-pc-windows-gnu:latest"

[target.aarch64-pc-windows-gnullvm]
image = "static-cross-aarch64-pc-windows-gnullvm:latest"

[target.x86_64-pc-windows-gnu.env]
passthrough = [
  "PKG_CONFIG_ALLOW_CROSS=1",
  "PKG_CONFIG_PATH=/usr/x86_64-w64-mingw32/lib/pkgconfig",
  "PKG_CONFIG_LIBDIR=/usr/x86_64-w64-mingw32/lib/pkgconfig",
  "PKG_CONFIG_PATH_x86_64_pc_windows_gnu=/usr/x86_64-w64-mingw32/lib/pkgconfig",
  "PKG_CONFIG_LIBDIR_x86_64_pc_windows_gnu=/usr/x86_64-w64-mingw32/lib/pkgconfig",
  "FFMPEG_PKG_CONFIG_PATH=/usr/x86_64-w64-mingw32/lib/pkgconfig",
  "FFMPEG_LIBS_DIR=/usr/x86_64-w64-mingw32/lib",
  "FFMPEG_INCLUDE_DIR=/usr/x86_64-w64-mingw32/include",
  "CFLAGS_x86_64_pc_windows_gnu=-DSIO_UDP_NETRESET=SIO_UDP_CONNRESET",
  "CXXFLAGS_x86_64_pc_windows_gnu=-DSIO_UDP_NETRESET=SIO_UDP_CONNRESET"
]