[package]
name = "gmv-steward"
version.workspace = true
edition.workspace = true
authors.workspace = true

[dependencies]
# base_mqtt = { git = "https://github.com/epimore/pigs.git", rev = "PIN_BEFORE_RELEASE" }
base_mqtt = { path = "../../pigs/base_mqtt" }
# base_rpc = { git = "https://github.com/epimore/pigs.git", rev = "6ef154f" }
base_rpc = { path = "../../pigs/base_rpc" }
gmv-protocol = { path = "../shared/protocol" }
gmv-nodec = { path = "../shared/nodec" }
tonic = "0.14"
prost = "0.14"
# base = { git = "https://github.com/epimore/pigs.git", rev = "6ef154f" }
base = { path = "../../pigs/base" }
# base_db = { git = "https://github.com/epimore/pigs.git", rev = "6ef154f", default-features = false, features = ["sqlite-bundled"] }
base_db = { path = "../../pigs/base_db", default-features = false, features = ["sqlite-bundled"] }
url.workspace = true
uuid.workspace = true

[dev-dependencies]
ed25519-dalek = "2"
tokio = { version = "1", features = ["macros", "rt-multi-thread"] }
