[package]
name = "gmv-nodec"
version.workspace = true
edition.workspace = true
authors.workspace = true

[dependencies]
base = { git = "https://github.com/epimore/pigs.git", rev = "6ef154f", features = [
    "net",
] }
# base = { path = "../../../pigs/base" }
base_rpc = { git = "https://github.com/epimore/pigs.git", rev = "6ef154f" }
gmv-protocol = { path = "../protocol" }
sys_metrics = { git = "https://github.com/epimore/pigs.git", rev = "6ef154f" }
tonic = "0.14"
tokio-stream = "0.1"
uuid = { version = "1.23", features = ["v7"] }
