[package]
name = "gmv-stream"
version.workspace = true
edition.workspace = true

[dependencies]
base_rpc = { git = "https://github.com/epimore/pigs.git", rev = "6ef154f" }
gmv-protocol = { path = "../shared/protocol" }
gmv-nodec = { path = "../shared/nodec" }
tonic = "0.14"
base = { git = "https://github.com/epimore/pigs.git", rev = "6ef154f", features = [
    "net",
] }
# base = { package = "base", path = "../../pigs/base", features = ["net"] }
gmv-domain = { path = "../shared/domain" }

futures-core = "0.3"
futures-util = "0.3"
tokio-stream = { version = "0.1", features = ["sync"] }
rsmpeg = { version = "0.14.2", default-features = false, features = [
    "link_system_ffmpeg",
] }
axum = { version = "0.8", features = ["ws"] }
axum-server = { workspace = true, features = ["tls-rustls"] }
rtp-types = "0.1"
socket2 = "0.6"
fs2 = "0.4"

# 共享依赖
parking_lot.workspace = true
url.workspace = true
crossbeam-channel.workspace = true
log = "0.4.28"

[dev-dependencies]
tokio = { version = "1.52.3", features = ["macros", "rt-multi-thread"] }
