log:
  level: warn
  stdout: true
  prefix: avai
  store_path: ./logs
  specify:
    - crate_name: avai
      level: info

guard:
  endpoint: http://127.0.0.1:18080

server:
  node_id: avai-node-1
  host: 127.0.0.1
  grpc_port: 19080
  capabilities:
    - ai.vehicle
