CREATE TABLE IF NOT EXISTS GB_SERVER (
    domain_id VARCHAR(20) NOT NULL PRIMARY KEY,
    domain VARCHAR(64) NOT NULL,
    sip_ip VARCHAR(64) NOT NULL,
    sip_port INTEGER NOT NULL,
    http_source VARCHAR(255) NOT NULL,
    status INTEGER NOT NULL,
    heart_time DATETIME NOT NULL,
    heart_cycle INTEGER NOT NULL
);

CREATE TABLE IF NOT EXISTS C_SEQ_CODE (
    seq_name VARCHAR(64) NOT NULL PRIMARY KEY,
    init_value BIGINT NOT NULL,
    current_value BIGINT NOT NULL,
    increment_value INTEGER NOT NULL,
    prefix_code VARCHAR(64) NULL,
    code_lenth INTEGER NULL,
    remark VARCHAR(255) NULL,
    create_date DATETIME NULL
);

CREATE TABLE IF NOT EXISTS GMV_OAUTH (
    DEVICE_ID VARCHAR(32) NOT NULL PRIMARY KEY,
    DOMAIN_ID VARCHAR(32) NOT NULL,
    DOMAIN VARCHAR(64) NOT NULL,
    PWD VARCHAR(128) NULL,
    PWD_CHECK INTEGER NOT NULL DEFAULT 0,
    ALIAS VARCHAR(128) NULL,
    STATUS INTEGER NOT NULL DEFAULT 1,
    HEARTBEAT_SEC INTEGER NOT NULL DEFAULT 60,
    DEL INTEGER NOT NULL DEFAULT 0
);

CREATE TABLE IF NOT EXISTS GMV_DEVICE (
    DEVICE_ID VARCHAR(32) NOT NULL PRIMARY KEY,
    TRANSPORT VARCHAR(16) NOT NULL,
    REGISTER_EXPIRES INTEGER NOT NULL,
    REGISTER_TIME DATETIME NOT NULL,
    ONLINE_EXPIRE_TIME DATETIME NULL,
    LOCAL_ADDR VARCHAR(64) NOT NULL,
    CONTACT_URI VARCHAR(256) NOT NULL,
    ENABLE_LR INTEGER NOT NULL DEFAULT 0,
    GB_VERSION VARCHAR(32) NULL,
    DEVICE_TYPE VARCHAR(64) NULL,
    MANUFACTURER VARCHAR(128) NULL,
    MODEL VARCHAR(128) NULL,
    FIRMWARE VARCHAR(128) NULL,
    MAX_CAMERA INTEGER NULL
);

CREATE TABLE IF NOT EXISTS GMV_DEVICE_CHANNEL (
    DEVICE_ID VARCHAR(32) NOT NULL,
    CHANNEL_ID VARCHAR(32) NOT NULL,
    NAME VARCHAR(128) NULL,
    MANUFACTURER VARCHAR(128) NULL,
    MODEL VARCHAR(128) NULL,
    OWNER VARCHAR(128) NULL,
    STATUS VARCHAR(16) NOT NULL,
    CIVIL_CODE VARCHAR(64) NULL,
    ADDRESS VARCHAR(255) NULL,
    PARENTAL INTEGER NULL,
    BLOCK VARCHAR(64) NULL,
    PARENT_ID VARCHAR(32) NULL,
    IP_ADDRESS VARCHAR(64) NULL,
    PORT INTEGER NULL,
    PASSWORD VARCHAR(128) NULL,
    LONGITUDE REAL NULL,
    LATITUDE REAL NULL,
    PTZ_TYPE INTEGER NULL,
    SUPPLY_LIGHT_TYPE INTEGER NULL,
    PRIMARY KEY (DEVICE_ID, CHANNEL_ID)
);

CREATE TABLE IF NOT EXISTS GMV_DEVICE_CHANNEL_CONF (
    DEVICE_ID VARCHAR(32) NOT NULL,
    CHANNEL_ID VARCHAR(32) NOT NULL,
    PRIMARY KEY (DEVICE_ID, CHANNEL_ID)
);

CREATE TABLE IF NOT EXISTS GMV_SIP_DIALOG_SESSION (
    STREAM_ID VARCHAR(64) NOT NULL PRIMARY KEY,
    DEVICE_ID VARCHAR(32) NOT NULL,
    CHANNEL_ID VARCHAR(32) NOT NULL,
    SESSION_TYPE VARCHAR(16) NOT NULL,
    SIGNAL_NODE_ID VARCHAR(64) NOT NULL,
    MEDIA_NODE_ID VARCHAR(64) NOT NULL,
    SSRC VARCHAR(16) NULL,
    CALL_ID VARCHAR(128) NOT NULL,
    LOCAL_URI VARCHAR(256) NOT NULL,
    REMOTE_URI VARCHAR(256) NOT NULL,
    LOCAL_TAG VARCHAR(128) NOT NULL,
    REMOTE_TAG VARCHAR(128) NULL,
    LOCAL_CSEQ BIGINT NOT NULL,
    REMOTE_CSEQ BIGINT NULL,
    CONTACT_URI VARCHAR(256) NULL,
    ROUTE_SET TEXT NULL,
    LOCAL_SIP_ADDR VARCHAR(64) NOT NULL,
    REMOTE_SIP_ADDR VARCHAR(64) NOT NULL,
    TRANSPORT VARCHAR(16) NOT NULL,
    STATE VARCHAR(16) NOT NULL,
    ESTABLISHED_AT DATETIME NULL,
    LAST_SEEN_AT DATETIME NOT NULL,
    EXPIRE_AT DATETIME NOT NULL,
    VERSION BIGINT NOT NULL,
    CREATED_AT DATETIME NOT NULL,
    UPDATED_AT DATETIME NOT NULL
);

CREATE INDEX IF NOT EXISTS IDX_GMV_SIP_DIALOG_CALL_ID ON GMV_SIP_DIALOG_SESSION (CALL_ID);
CREATE INDEX IF NOT EXISTS IDX_GMV_SIP_DIALOG_OWNER ON GMV_SIP_DIALOG_SESSION (SIGNAL_NODE_ID, STATE, STREAM_ID);
CREATE INDEX IF NOT EXISTS IDX_GMV_SIP_DIALOG_SSRC ON GMV_SIP_DIALOG_SESSION (SIGNAL_NODE_ID, MEDIA_NODE_ID, SSRC, STATE, EXPIRE_AT);
