CREATE TABLE IF NOT EXISTS GMV_FILE_INFO (
  ID BIGINT NOT NULL PRIMARY KEY,
  DEVICE_ID VARCHAR(20) NOT NULL,
  CHANNEL_ID VARCHAR(20) NOT NULL,
  BIZ_TIME DATETIME NULL,
  BIZ_ID VARCHAR(128) NOT NULL,
  FILE_TYPE INTEGER NULL,
  FILE_SIZE BIGINT NULL,
  FILE_NAME VARCHAR(128) NOT NULL,
  FILE_FORMAT VARCHAR(32) NULL,
  DIR_PATH VARCHAR(255) NOT NULL,
  ABS_PATH VARCHAR(255) NULL,
  NOTE VARCHAR(128) NULL,
  IS_DEL INTEGER NULL DEFAULT 0,
  CREATE_TIME DATETIME NULL
);

CREATE TABLE IF NOT EXISTS GMV_RECORD (
  BIZ_ID VARCHAR(128) NOT NULL PRIMARY KEY,
  DEVICE_ID VARCHAR(20) NOT NULL,
  CHANNEL_ID VARCHAR(20) NOT NULL,
  USER_ID VARCHAR(32) NULL,
  ST DATETIME NULL,
  ET DATETIME NULL,
  SPEED INTEGER NULL,
  CT DATETIME NULL,
  STATE INTEGER NULL,
  LT DATETIME NULL,
  STREAM_APP_NAME VARCHAR(64) NULL
);

CREATE TABLE IF NOT EXISTS GMV_DEVICE_PTZ_PRESET (
  ID BIGINT NOT NULL PRIMARY KEY,
  DEVICE_ID VARCHAR(20) NOT NULL,
  CHANNEL_ID VARCHAR(20) NOT NULL,
  PRESET_NO INTEGER NOT NULL,
  PRESET_NAME VARCHAR(64) NULL,
  ENABLED INTEGER NOT NULL DEFAULT 1,
  SORT_NO INTEGER NULL DEFAULT 0,
  REMARK VARCHAR(255) NULL,
  CREATE_TIME DATETIME NOT NULL,
  UPDATE_TIME DATETIME NOT NULL,
  UNIQUE (DEVICE_ID, CHANNEL_ID, PRESET_NO)
);
