CREATE TABLE IF NOT EXISTS GB28181_SEQ_CODE (
    seq_id INTEGER PRIMARY KEY AUTOINCREMENT,
    seq_name VARCHAR(64) NOT NULL UNIQUE,
    init_value BIGINT NOT NULL,
    current_value BIGINT NOT NULL,
    increment_value INTEGER NOT NULL DEFAULT 1,
    prefix_code VARCHAR(64) NULL,
    code_lenth INTEGER NULL,
    remark VARCHAR(256) NULL,
    create_date DATETIME NULL
);

CREATE TABLE IF NOT EXISTS GB28181_OAUTH (
    DEVICE_ID VARCHAR(20) NOT NULL PRIMARY KEY,
    DOMAIN_ID VARCHAR(20) NOT NULL DEFAULT '34020000002000000001',
    DOMAIN VARCHAR(20) NOT NULL,
    longitude DECIMAL(12, 8) NULL,
    latitude DECIMAL(12, 8) NULL,
    address VARCHAR(255) NULL,
    PWD VARCHAR(120) NULL,
    PWD_CHECK INTEGER NULL,
    ALIAS VARCHAR(32) NULL,
    STATUS INTEGER NULL,
    HEARTBEAT_SEC INTEGER NULL,
    DEL INTEGER NULL,
    CREATE_TIME DATETIME NULL,
    tenant_id INTEGER NULL,
    sys_org_code VARCHAR(64) NULL,
    create_by VARCHAR(64) NULL,
    update_by VARCHAR(64) NULL,
    update_time DATETIME NULL
);

CREATE TABLE IF NOT EXISTS GB28181_DEVICE (
    DEVICE_ID VARCHAR(20) NOT NULL PRIMARY KEY,
    TRANSPORT VARCHAR(3) NULL,
    REGISTER_EXPIRES INTEGER NULL,
    REGISTER_TIME DATETIME NULL,
    LOCAL_ADDR VARCHAR(32) NULL,
    CONTACT_URI VARCHAR(128) NULL,
    ENABLE_LR INTEGER NULL,
    DEVICE_TYPE VARCHAR(16) NULL,
    MANUFACTURER VARCHAR(32) NULL,
    MODEL VARCHAR(64) NULL,
    FIRMWARE VARCHAR(64) NULL,
    MAX_CAMERA INTEGER NULL,
    ONLINE_EXPIRE_TIME DATETIME NULL,
    GB_VERSION VARCHAR(32) NULL DEFAULT '2.0',
    LAST_UPDATE_TIME DATETIME NULL,
    CREATE_TIME DATETIME NULL,
    tenant_id INTEGER NULL,
    sys_org_code VARCHAR(64) NULL,
    create_by VARCHAR(64) NULL,
    update_by VARCHAR(64) NULL,
    update_time DATETIME NULL
);

CREATE TABLE IF NOT EXISTS GB28181_DEVICE_CHANNEL (
    DEVICE_ID VARCHAR(20) NOT NULL,
    CHANNEL_ID VARCHAR(20) NOT NULL,
    NAME VARCHAR(32) NULL,
    MANUFACTURER VARCHAR(32) NULL,
    MODEL VARCHAR(64) NULL,
    OWNER VARCHAR(32) NULL,
    STATUS VARCHAR(32) NULL DEFAULT 'ON',
    CIVIL_CODE VARCHAR(32) NULL,
    ADDRESS VARCHAR(32) NULL,
    PARENTAL CHAR(1) NULL,
    BLOCK VARCHAR(32) NULL,
    PARENT_ID VARCHAR(32) NULL,
    IP_ADDRESS VARCHAR(32) NULL,
    PORT INTEGER NULL,
    PASSWORD VARCHAR(32) NULL,
    LONGITUDE DECIMAL(12, 6) NULL,
    LATITUDE DECIMAL(12, 6) NULL,
    PTZ_TYPE CHAR(1) NULL,
    SUPPLY_LIGHT_TYPE CHAR(1) NULL,
    PRIMARY KEY (DEVICE_ID, CHANNEL_ID)
);

CREATE TABLE IF NOT EXISTS GB28181_DEVICE_CHANNEL_CONF (
    DEVICE_ID VARCHAR(20) NOT NULL,
    CHANNEL_ID VARCHAR(20) NOT NULL,
    ALIAS_NAME VARCHAR(16) NULL,
    PTZ_ENABLE INTEGER NULL DEFAULT 2,
    TALK_ENABLE INTEGER NULL DEFAULT 2,
    AUDIO_ENABLE INTEGER NULL DEFAULT 2,
    SNAPSHOT_ENABLE INTEGER NULL DEFAULT 2,
    RECORD_ENABLE INTEGER NULL DEFAULT 2,
    PLAYBACK_ENABLE INTEGER NULL DEFAULT 2,
    ALARM_ENABLE INTEGER NULL DEFAULT 2,
    BIZ_ENABLE INTEGER NULL DEFAULT 1,
    SORT_NO INTEGER NULL DEFAULT 0,
    over_pic_id BIGINT NULL,
    CREATE_TIME DATETIME NULL DEFAULT CURRENT_TIMESTAMP,
    UPDATE_TIME DATETIME NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (DEVICE_ID, CHANNEL_ID),
    FOREIGN KEY (DEVICE_ID, CHANNEL_ID) REFERENCES GB28181_DEVICE_CHANNEL (DEVICE_ID, CHANNEL_ID) ON DELETE CASCADE
);

CREATE INDEX IF NOT EXISTS idx_gb28181_dcc_sort ON GB28181_DEVICE_CHANNEL_CONF (DEVICE_ID, SORT_NO, CHANNEL_ID);

CREATE TABLE IF NOT EXISTS GB28181_DEVICE_PTZ_PRESET (
    ID INTEGER PRIMARY KEY AUTOINCREMENT,
    DEVICE_ID VARCHAR(20) NOT NULL,
    CHANNEL_ID VARCHAR(20) NOT NULL,
    PRESET_NO INTEGER NOT NULL,
    PRESET_NAME VARCHAR(64) NULL,
    ENABLED INTEGER NOT NULL DEFAULT 1,
    SORT_NO INTEGER NULL DEFAULT 0,
    REMARK VARCHAR(255) NULL,
    CREATE_TIME DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    UPDATE_TIME DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    UNIQUE (DEVICE_ID, CHANNEL_ID, PRESET_NO),
    FOREIGN KEY (DEVICE_ID, CHANNEL_ID) REFERENCES GB28181_DEVICE_CHANNEL (DEVICE_ID, CHANNEL_ID) ON DELETE CASCADE
);

CREATE INDEX IF NOT EXISTS idx_gb28181_ptz_preset_channel ON GB28181_DEVICE_PTZ_PRESET (DEVICE_ID, CHANNEL_ID, ENABLED, SORT_NO);

CREATE TABLE IF NOT EXISTS GB28181_FILE_INFO (
    ID INTEGER PRIMARY KEY AUTOINCREMENT,
    DEVICE_ID VARCHAR(20) NOT NULL,
    CHANNEL_ID VARCHAR(20) NOT NULL,
    BIZ_TIME DATETIME NULL,
    BIZ_ID VARCHAR(128) NOT NULL,
    FILE_TYPE INTEGER NULL,
    FILE_SIZE BIGINT NULL,
    FILE_NAME VARCHAR(128) NOT NULL,
    FILE_FORMAT VARCHAR(32) NULL,
    DIR_PATH VARCHAR(255) NOT NULL,
    ABS_PATH VARCHAR(255) NULL,
    NOTE VARCHAR(128) NULL,
    IS_DEL INTEGER NULL DEFAULT 0,
    CREATE_TIME DATETIME NULL
);

CREATE INDEX IF NOT EXISTS idx_gb28181_file_dc ON GB28181_FILE_INFO (DEVICE_ID, CHANNEL_ID);
CREATE INDEX IF NOT EXISTS idx_gb28181_file_device_channel_id ON GB28181_FILE_INFO (DEVICE_ID, CHANNEL_ID, ID DESC);

CREATE TABLE IF NOT EXISTS GB28181_RECORD (
    BIZ_ID VARCHAR(128) NOT NULL PRIMARY KEY,
    DEVICE_ID VARCHAR(20) NOT NULL,
    CHANNEL_ID VARCHAR(20) NOT NULL,
    USER_ID VARCHAR(32) NULL,
    ST DATETIME NULL,
    ET DATETIME NULL,
    SPEED INTEGER NULL,
    CT DATETIME NULL,
    STATE INTEGER NULL,
    LT DATETIME NULL,
    STREAM_APP_NAME VARCHAR(64) NULL
);

CREATE TABLE IF NOT EXISTS GB28181_SIP_DIALOG_SESSION (
    STREAM_ID VARCHAR(64) NOT NULL PRIMARY KEY,
    DEVICE_ID VARCHAR(32) NOT NULL,
    CHANNEL_ID VARCHAR(32) NOT NULL,
    SESSION_TYPE VARCHAR(16) NOT NULL,
    SIGNAL_NODE_ID VARCHAR(64) NOT NULL,
    MEDIA_NODE_ID VARCHAR(64) NOT NULL,
    SSRC VARCHAR(16) NULL,
    CALL_ID VARCHAR(128) NOT NULL,
    LOCAL_URI VARCHAR(256) NOT NULL,
    REMOTE_URI VARCHAR(256) NOT NULL,
    LOCAL_TAG VARCHAR(128) NOT NULL,
    REMOTE_TAG VARCHAR(128) NULL,
    LOCAL_CSEQ BIGINT NOT NULL DEFAULT 1,
    REMOTE_CSEQ BIGINT NULL,
    CONTACT_URI VARCHAR(256) NULL,
    ROUTE_SET TEXT NULL,
    LOCAL_SIP_ADDR VARCHAR(64) NOT NULL,
    REMOTE_SIP_ADDR VARCHAR(64) NOT NULL,
    TRANSPORT VARCHAR(8) NOT NULL,
    STATE VARCHAR(32) NOT NULL,
    ESTABLISHED_AT DATETIME NULL,
    LAST_SEEN_AT DATETIME NOT NULL,
    EXPIRE_AT DATETIME NOT NULL,
    VERSION BIGINT NOT NULL DEFAULT 0,
    CREATED_AT DATETIME NOT NULL,
    UPDATED_AT DATETIME NOT NULL
);

CREATE INDEX IF NOT EXISTS IDX_GB28181_SIP_DIALOG_DEVICE_STATE ON GB28181_SIP_DIALOG_SESSION (DEVICE_ID, STATE);
CREATE INDEX IF NOT EXISTS IDX_GB28181_SIP_DIALOG_CALL_ID ON GB28181_SIP_DIALOG_SESSION (CALL_ID);
CREATE INDEX IF NOT EXISTS IDX_GB28181_SIP_DIALOG_OWNER_STATE_EXPIRE ON GB28181_SIP_DIALOG_SESSION (SIGNAL_NODE_ID, STATE, EXPIRE_AT);
CREATE INDEX IF NOT EXISTS IDX_GB28181_SIP_DIALOG_OWNER_SSRC_STATE_EXPIRE ON GB28181_SIP_DIALOG_SESSION (SIGNAL_NODE_ID, SSRC, STATE, EXPIRE_AT);
CREATE INDEX IF NOT EXISTS IDX_GB28181_SIP_DIALOG_OWNER ON GB28181_SIP_DIALOG_SESSION (SIGNAL_NODE_ID, STATE, STREAM_ID);
CREATE INDEX IF NOT EXISTS IDX_GB28181_SIP_DIALOG_SSRC ON GB28181_SIP_DIALOG_SESSION (SIGNAL_NODE_ID, MEDIA_NODE_ID, SSRC, STATE, EXPIRE_AT);